/*******************************************************************************
 DO NOT EDIT
 This file was automatically generated by the Impulse C Compiler.

 Copyright (c) 2002-2013 by Impulse Accelerated Technologies, Inc.
 All rights reserved.

 This source file may be used and redistributed without charge
 subject to the provisions of the IMPULSE ACCELERATED TECHNOLOGIES,
 INC. REDISTRIBUTABLE IP LICENSE AGREEMENT, and provided that this
 copyright statement is not removed from the file, and that any
 derivative work contains this copyright notice.

 Stage Master is Copyright 2002-2005, Green Mountain Computing Systems, Inc.
 All rights reserved.
********************************************************************************/

#include "co.h"

/* Architecture Includes */
#include "Blokus_module.h"


extern void *co_memory_ext7_alloc(size_t);
extern void *co_memory_ext8_alloc(size_t);
extern void *co_memory_ext9_alloc(size_t);
extern void *co_memory_ext0_alloc(size_t);
extern void *co_memory_ext1_alloc(size_t);
extern void *co_memory_ext10_alloc(size_t);
extern void *co_memory_ext2_alloc(size_t);
extern void *co_memory_ext11_alloc(size_t);
extern void *co_memory_ext12_alloc(size_t);
extern void *co_memory_ext3_alloc(size_t);
extern void *co_memory_ext13_alloc(size_t);
extern void *co_memory_ext4_alloc(size_t);
extern void *co_memory_ext14_alloc(size_t);
extern void *co_memory_ext5_alloc(size_t);
extern void *co_memory_ext15_alloc(size_t);
extern void *co_memory_ext6_alloc(size_t);

/* Run Procedures */
extern void producer_func(co_stream);
extern void consumer_func(co_stream);
extern void make_move_func(co_stream, co_stream, co_stream, co_stream, co_stream, co_stream, co_stream, co_stream);
extern void timer_func(co_stream, co_stream);
extern void minimax_func(co_stream, co_stream, co_stream, co_stream, co_stream, co_stream, co_stream, co_stream, co_stream, co_stream);
extern void minimax_ex_func(co_stream, co_stream, co_stream, co_stream, co_stream, co_stream);
extern void eval_func(co_stream, co_stream);

/* *********************************************************************************
 * This function is intended to be used with the NIOS II driver model 
 *  which automatically calls each module as a separate instance of its
 *  driver through the *_INIT() and *_INSTANCE() macros located in the file
 *  Blokus_module.h generated during software export
 * ****************************************************************************** */
void Blokus_module_co_init(struct Blokus_module_config_s *cfg)

{
  co_stream input_stream;
  co_stream output_stream;

  input_stream=co_stream_create("input_stream",INT_TYPE(8),1);
  output_stream=co_stream_create("output_stream",INT_TYPE(8),1);
  co_process_create("producer",(co_function)producer_func,
                    1,
                    input_stream);
  co_process_create("consumer",(co_function)consumer_func,
                    1,
                    output_stream);

  /* Architecture Initialization */
  co_stream_attach(input_stream, cfg->input_stream.base, cfg->input_stream.dir);
  co_stream_attach(output_stream, cfg->output_stream.base, cfg->output_stream.dir);
}
